const diTokens = {
    PRODUCT_DAO_TOKEN: 'PRODUCT_DAO_TOKEN',
    PRODUCT_BO_TOKEN: 'PRODUCT_BO_TOKEN',
    PRODUCT_CONTROLLER_TOKEN: 'PRODUCT_CONTROLLER_TOKEN',
    USER_DAO_TOKEN: 'USER_DAO_TOKEN',
    USER_BO_TOKEN: 'USER_BO_TOKEN',
    USER_CONTROLLER_TOKEN: 'USER_CONTROLLER_TOKEN',
    AUTH_MIDDLEWARE_TOKEN: 'AUTH_MIDDLEWARE_TOKEN',
    APP_ROUTES_TOKEN: 'APP_ROUTES_TOKEN'
}

export default diTokens